import type { Metadata } from "next";
import "./globals.css";
import Footer from "@/components/Footer/Footer";
import Navbar from "@/components/Navbar/Navbar";
/* import BarraDeBusqueda from "@/components/BarraDeBusqueda/BarraDeBusqueda"; */
import SearchBar from "@/components/SearchBar/SearchBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-white flex flex-col items-center justify-between w-full font-sans">
        <Navbar />
        {/* <BarraDeBusqueda/> */}
        <SearchBar/>
        {children}
        <Footer />
      </body>
    </html>
  );
}


